### ISSUE TITLE
Application Fails to Exit

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#49]
Under some circumstance, the application will not gracefully exit when selecting File->Exit.

**Comment by Kroronos** [comment]
Observed during demo in discussion section on 20/02/2018.
Flow of program included -> failed login -> login into Feeney's account -> calendar interaction -> new user dialogue -> fail new user creation (password didn't meet critereon) -> sucessful user creation (Brett Benda) -> sorting lists -> switch into devHomeView->(File->Exit) 

File->Exit failed to produce any result, despite repeated attempts, program exited gracefully when the x was clicked in the process window.

**Comment by fallinbryan** [comment]
Followed the same path (except logging in with Feeney's account) unable to duplicate bug.  Attempted many other paths.  Unable to duplicate bug on my pc.
OS: Windows10
Python: 3.6.4  `python --version`
pip version: 9.0.1 `pip --version`
MySQLdb version: 1.3.12 
`import MySQLdb`
`MySQLdb.__version__`
matplotlib version: 2.1.2
`import matplotlib`
`matplotlib.__version__`
tkinter version: 8.6
`import tkinter`
`tkinter.TkVersion`

**Comment by fallinbryan** [comment]
To aid in troubleshooting this bug and since I was not able to reproduce the bug in my environment, I pushed a commit to Scrumbles.py that contains a block of assertions that will not allow the code execute unless module versions match.

**Comment by Kroronos** [comment]
Think I found out why the issue was observed, when you try to create a new user and fail the creation pop-up gets hidden behind the main view and only the main view and error pop-up are visible. When you close the error pop-up, the user may not realize the user creation screen is still open. While this is open, File->Exit while not work.

Proposed solutions: Find way to keep pop-up visible when error message appears, or figure out way to make exit close all open windows for program.
![state_directly_after_failure](https://user-images.githubusercontent.com/24195520/36516795-8d694c96-174d-11e8-9b12-cbf9fb2f4edb.PNG)

**Comment by fallinbryan** [comment]
!!!  I noticed that the dialog gets hidden on a fail!  I meant to open a ticket on that!  That very likely could be the cause!  I will attempt straight away

**Comment by fallinbryan** [comment]
Replicated issue.   It is the hidden dialog blocking the exit function from destroying all open windows.

**Comment by fallinbryan** [comment]
Root cause discovered.  This issue has been split to issue #54  and #55 

Closing Issue: Root Cause Discovered. Fix to be implemented on other referenced tickets.
