### ISSUE TITLE
Make Better Update Policy

### ISSUE THREAD

**Issue by ryanqfeeney** [CEN3031-group16/GroupProject#60]
Current project just updates every 5 seconds, will enhance.

**Comment by fallinbryan** [comment]
[Asynchronous Databases and Python](http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/)

**Comment by fallinbryan** [comment]
Branch RemoteUpdates.  Wrote a server side service that will sniff port 3306 for incoming packets that contain keywords that indicate a change to database is in progress.  If a keyword is detected, service will send a change message on TCP port 5005.

Included getChageUpdate.py in the test folder to demonstrate.  To try it out, execute the script.  The script will run for 250 seconds.  While the script is running, make a change to the database and watch the change notification come in real time.

This socket can be added to a thread started from Scrumbles.py and then notify the Scrumbles app that a change has occurred on the database.  Once a change notification/event has been received,  Scrumbles can then update her internal tables instead of the brute force check every 5 seconds method.

**Comment by fallinbryan** [comment]
Closure pending review and approvals of Remote updates #101
